/**********************************************************************
 * Copyright (C) 2026 Red Hat, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 ***********************************************************************/

import { execFileSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as path from 'node:path';

import type { Locator, Page } from '@playwright/test';
import type { NavigationBar, Runner } from '@podman-desktop/tests-playwright';
import { PreferencesPage, RunnerOptions, StatusBar } from '@podman-desktop/tests-playwright';

import { configureVideoCaptions, expect, frameForCaption, test } from './video-captions/runtime';

const EXTENSION_PREINSTALLED = process.env.EXTENSION_PREINSTALLED === 'true';
const EXTENSION_LABEL = 'podman-desktop.kreate';
const CONFIG_MAP_NAME = 'kreate-e2e';
const BATCH_CONFIG_MAP_NAMES = ['kreate-batch-one', 'kreate-batch-two'];
const SECRET_NAME = 'kreate-secret';
const SECRET_VALUE = 'test-token-value';
const NAMESPACE_NAME = 'kreate-namespace';
const POD_NAME = 'kreate-discovered-pod';
const POD_IMAGE = 'registry.k8s.io/pause:3.9';
const sourceKubeconfig = process.env.E2E_KUBECONFIG;
const profileKubeconfig = path.resolve('tests', 'playwright', 'resources', 'kube-config');

interface KubernetesResource {
  data?: Record<string, string>;
  metadata?: { name?: string };
  spec?: { containers?: Array<{ image?: string }> };
}

function kubectlBinary(): string {
  const assets = process.env.KUBEBUILDER_ASSETS;
  return assets ? path.join(assets, process.platform === 'win32' ? 'kubectl.exe' : 'kubectl') : 'kubectl';
}

function kubectlResource(kind: string, name: string): KubernetesResource {
  if (!sourceKubeconfig) throw new Error('E2E_KUBECONFIG is required');
  const result = execFileSync(kubectlBinary(), ['get', kind, name, '--output=json'], {
    env: { ...process.env, KUBECONFIG: sourceKubeconfig },
    encoding: 'utf8',
  });
  return JSON.parse(result) as KubernetesResource;
}

function prepareKubeconfig(): void {
  if (!sourceKubeconfig) throw new Error('Set E2E_KUBECONFIG to a kubeconfig generated by envtest-start');
  const result = execFileSync(
    kubectlBinary(),
    ['--kubeconfig', sourceKubeconfig, 'config', 'view', '--raw', '--minify', '--output=json'],
    { encoding: 'utf8' },
  );
  const server = (JSON.parse(result) as { clusters?: Array<{ cluster?: { server?: string } }> }).clusters?.[0]?.cluster
    ?.server;
  if (!server || !['127.0.0.1', 'localhost', '[::1]'].includes(new URL(server).hostname)) {
    throw new Error('E2E_KUBECONFIG must point to a local envtest API server');
  }
  fs.mkdirSync(path.dirname(profileKubeconfig), { recursive: true });
  fs.copyFileSync(sourceKubeconfig, profileKubeconfig);
}

async function selectYamlLine(editor: Locator, line: string): Promise<void> {
  await editor.evaluate((element: HTMLTextAreaElement, selectedLine) => {
    const offset = element.value.indexOf(selectedLine);
    if (offset < 0) throw new Error(`YAML line not found: ${selectedLine}`);
    element.focus();
    element.setSelectionRange(offset, offset);
    element.dispatchEvent(new Event('selectionchange', { bubbles: true }));
  }, line);
}

async function openKreateWebview(runner: Runner, mainPage: Page, navigationBar: NavigationBar): Promise<Page> {
  const navigationButton = navigationBar.navigationLocator.getByRole('link', { name: 'Kreate', exact: true });
  await expect(navigationButton).toBeEnabled();
  await navigationButton.click();
  await expect(mainPage.getByRole('document', { name: 'Webview Kreate' })).toBeVisible();

  await expect
    .poll(
      async () => {
        for (const candidate of runner.getWindows().slice(1)) {
          if ((await candidate.getByRole('heading', { name: 'Create Kubernetes resources' }).count()) > 0) {
            return true;
          }
        }
        return false;
      },
      { timeout: 30_000 },
    )
    .toBe(true);

  for (const candidate of runner.getWindows().slice(1)) {
    if ((await candidate.getByRole('heading', { name: 'Create Kubernetes resources' }).count()) > 0) {
      return candidate;
    }
  }
  throw new Error('Kreate webview window was not found');
}

test.use({
  runnerOptions: new RunnerOptions({
    customFolder: 'kreate-tests',
    customSettings: {
      'extensions.disabled': [
        'podman-desktop.compose',
        'podman-desktop.docker',
        'podman-desktop.kind',
        'podman-desktop.lima',
        'podman-desktop.minikube',
        'podman-desktop.registries',
      ],
    },
  }),
});

test.describe.serial('Kreate extension', { tag: '@integration' }, () => {
  let webview: Page;
  let generatedYaml: string;

  test.beforeEach(({ page }, testInfo) => {
    configureVideoCaptions(page, testInfo);
  });

  test.beforeAll(async ({ runner, welcomePage }) => {
    test.setTimeout(120_000);
    prepareKubeconfig();
    runner.setVideoAndTraceName('kreate-e2e');
    await welcomePage.handleWelcomePage(true);
  });

  test.afterAll(async ({ runner }) => {
    test.setTimeout(120_000);
    await runner.close();
  });

  test('Install and verify Kreate', async ({ navigationBar }) => {
    test.setTimeout(180_000);
    const extensionsPage = await navigationBar.openExtensions();
    if (!EXTENSION_PREINSTALLED) {
      const image = process.env.EXTENSION_OCI_IMAGE;
      if (!image) throw new Error('Set EXTENSION_OCI_IMAGE or EXTENSION_PREINSTALLED=true');
      await extensionsPage.installExtensionFromOCIImage(image);
    }
    await expect
      .poll(async () => extensionsPage.extensionIsInstalled(EXTENSION_LABEL), { timeout: 60_000 })
      .toBeTruthy();
    const extension = await extensionsPage.getInstalledExtension('Kreate', EXTENSION_LABEL);
    await expect(extension.status).toHaveText('ACTIVE');
  });

  test('Load a Kubernetes context and open the Kreate webview', async ({ page, navigationBar, runner }) => {
    const settingsBar = await navigationBar.openSettings();
    await settingsBar.expandPreferencesTab();
    const preferencesPage = await settingsBar.openTabPage(PreferencesPage);
    await preferencesPage.selectKubeFile(profileKubeconfig);
    await new StatusBar(page).validateKubernetesContext('envtest');

    webview = await openKreateWebview(runner, page, navigationBar);
    await expect(webview.getByRole('heading', { name: 'Create Kubernetes resources' })).toBeVisible();
  });

  test('Generate a ConfigMap manifest from a template', async () => {
    await test.step(
      'Create a ConfigMap manifest from a template',
      async () => {
        await webview.getByRole('button', { name: 'Use template' }).click();
        await expect(webview.getByRole('heading', { name: 'Use a template' })).toBeVisible();
        await webview.getByRole('button', { name: 'Resource to create:', exact: true }).click();
        await webview.getByRole('button', { name: 'configmap', exact: true }).click();
        await webview.getByLabel('Name').fill(CONFIG_MAP_NAME);
        // The first key input is for literal values; the second is for optional file input.
        await webview.getByPlaceholder('key').first().fill('message');
        await webview.getByPlaceholder('value').fill('from-template');
        await webview.getByRole('button', { name: 'view-yaml' }).click();

        const yamlEditor = webview.locator('textarea');
        await expect(yamlEditor).toHaveValue(/kind: ConfigMap/);
        await expect(yamlEditor).toHaveValue(new RegExp(`name: ${CONFIG_MAP_NAME}`));
        await frameForCaption(yamlEditor);
        await expect(yamlEditor, 'The generated ConfigMap includes the template values').toHaveValue(
          /message: from-template/,
        );
        generatedYaml = await yamlEditor.inputValue();
      },
      { params: { videoCaption: true } },
    );
  });

  test('Show the ConfigMap specification beside the YAML editor', async () => {
    await test.step(
      'Inspect the ConfigMap and its selected YAML fields',
      async () => {
        const yamlEditor = webview.locator('textarea');
        const specPanel = webview.getByRole('region', { name: 'Resource specification' });
        const specTitle = specPanel.locator('span.font-bold').first();

        await selectYamlLine(yamlEditor, 'kind: ConfigMap');
        await expect(specTitle).toHaveText('ConfigMap');
        await expect(specPanel.getByText('metadata', { exact: true })).toBeVisible();
        await expect(specPanel.getByText('data', { exact: true })).toBeVisible();

        await selectYamlLine(yamlEditor, `name: ${CONFIG_MAP_NAME}`);
        await expect(specTitle).toHaveText('metadata');
        await selectYamlLine(yamlEditor, 'message: from-template');
        await expect(specTitle).toHaveText('data');
      },
      { params: { videoCaption: true } },
    );
  });

  test('Edit and apply the ConfigMap to Kubernetes', async () => {
    await test.step(
      'Apply the edited ConfigMap to the cluster',
      async () => {
        const yamlEditor = webview.locator('textarea');
        await yamlEditor.fill(generatedYaml.replace('from-template', 'edited-in-kreate'));
        await webview.getByRole('button', { name: 'Apply to cluster' }).click();
        await expect(
          webview.getByText('The resource has been successfully applied to the cluster'),
          'Kreate confirms that the ConfigMap was applied',
        ).toBeVisible();
      },
      { params: { videoCaption: true } },
    );
    await expect.poll(() => kubectlResource('configmap', CONFIG_MAP_NAME).data?.message).toBe('edited-in-kreate');
  });

  test('Reject invalid YAML, then apply multiple ConfigMaps from the editor', async () => {
    await test.step(
      'Correct invalid YAML and apply two ConfigMaps',
      async () => {
        const yamlEditor = webview.locator('textarea');
        const applyButton = webview.getByRole('button', { name: 'Apply to cluster' });

        await yamlEditor.fill('not-a-kubernetes-resource');
        await applyButton.click();
        await expect(webview.getByText('No valid Kubernetes resources found in content')).toBeVisible();

        await yamlEditor.fill(
          BATCH_CONFIG_MAP_NAMES.map(
            (name, index) =>
              `apiVersion: v1\nkind: ConfigMap\nmetadata:\n  name: ${name}\ndata:\n  source: editor-${index + 1}\n`,
          ).join('---\n'),
        );
        await expect(applyButton).toBeEnabled();
        await frameForCaption(yamlEditor);
        await applyButton.click();
        await expect(webview.getByText('The resource has been successfully applied to the cluster')).toBeVisible();
        await expect(webview.getByText('No valid Kubernetes resources found in content')).toHaveCount(0);
      },
      { params: { videoCaption: true } },
    );

    for (const [index, name] of BATCH_CONFIG_MAP_NAMES.entries()) {
      await expect.poll(() => kubectlResource('configmap', name).data?.source).toBe(`editor-${index + 1}`);
    }
  });

  test('Generate and apply a generic Secret from a nested template', async () => {
    await test.step(
      'Create a generic Secret from a template',
      async () => {
        await webview.getByRole('button', { name: 'Use template' }).click();
        await webview.getByRole('button', { name: 'Resource to create:', exact: true }).click();
        await webview.getByRole('button', { name: 'secret', exact: true }).click();
        await webview.getByRole('button', { name: '(select a resource type)', exact: true }).click();
        await webview.getByRole('button', { name: 'generic', exact: true }).click();
        await webview.getByLabel('Name').fill(SECRET_NAME);
        await webview.getByPlaceholder('key').first().fill('token');
        const secretValue = webview.getByPlaceholder('value');
        await expect(secretValue).toHaveAttribute('type', 'password');
        await secretValue.fill(SECRET_VALUE);
        await webview.getByRole('button', { name: 'view-yaml' }).click();

        const yamlEditor = webview.locator('textarea');
        await expect(yamlEditor).toHaveValue(/kind: Secret/);
        await expect(yamlEditor).toHaveValue(new RegExp(`name: ${SECRET_NAME}`));
        await expect(yamlEditor).toHaveValue(/token:/);
        await frameForCaption(yamlEditor);
        await webview.getByRole('button', { name: 'Apply to cluster' }).click();
        await expect(webview.getByText('The resource has been successfully applied to the cluster')).toBeVisible();
      },
      { params: { videoCaption: true } },
    );

    await expect
      .poll(() => {
        const encoded = kubectlResource('secret', SECRET_NAME).data?.token;
        return encoded ? Buffer.from(encoded, 'base64').toString('utf8') : undefined;
      })
      .toBe(SECRET_VALUE);
  });

  test('Recover from a template error and create a Namespace', async () => {
    await test.step(
      'Provide the missing Namespace name and apply the generated manifest',
      async () => {
        await webview.getByRole('button', { name: 'Use template' }).click();
        await webview.getByRole('button', { name: 'Resource to create:', exact: true }).click();
        await webview.getByRole('button', { name: 'namespace', exact: true }).click();
        await webview.getByRole('button', { name: 'view-yaml' }).click();
        await expect(webview.getByText(/execute command error:/)).toBeVisible();

        await webview.getByLabel('Name').fill(NAMESPACE_NAME);
        await webview.getByRole('button', { name: 'view-yaml' }).click();
        const yamlEditor = webview.locator('textarea');
        await expect(yamlEditor).toHaveValue(/kind: Namespace/);
        await expect(yamlEditor).toHaveValue(new RegExp(`name: ${NAMESPACE_NAME}`));
        await frameForCaption(yamlEditor);
        await webview.getByRole('button', { name: 'Apply to cluster' }).click();
        await expect(webview.getByText('The resource has been successfully applied to the cluster')).toBeVisible();
      },
      { params: { videoCaption: true } },
    );

    await expect.poll(() => kubectlResource('namespace', NAMESPACE_NAME).metadata?.name).toBe(NAMESPACE_NAME);
  });

  test('Discover a Pod resource and apply its completed YAML', async () => {
    await test.step(
      'Select a Pod from the resource catalog and complete its manifest',
      async () => {
        await webview.getByRole('button', { name: 'Use template' }).click();
        await webview.getByRole('button', { name: 'Resource to create:', exact: true }).click();
        await webview.getByRole('button', { name: 'other...', exact: true }).click();
        const resourceDialog = webview.getByRole('dialog', { name: 'Select a resource' });
        await resourceDialog.getByRole('button', { name: 'v1 Pod', exact: true }).click();

        const yamlEditor = webview.locator('textarea');
        await expect(yamlEditor).toHaveValue(/kind: Pod/);
        await yamlEditor.fill(
          [
            'apiVersion: v1',
            'kind: Pod',
            'metadata:',
            `  name: ${POD_NAME}`,
            'spec:',
            '  containers:',
            '    - name: pause',
            `      image: ${POD_IMAGE}`,
            '',
          ].join('\n'),
        );
        await frameForCaption(yamlEditor);
        await webview.getByRole('button', { name: 'Apply to cluster' }).click();
        await expect(webview.getByText('The resource has been successfully applied to the cluster')).toBeVisible();
      },
      { params: { videoCaption: true } },
    );

    await expect.poll(() => kubectlResource('pod', POD_NAME).spec?.containers?.[0]?.image).toBe(POD_IMAGE);
  });

  test('Show the Pod specification for the selected container field', async () => {
    await test.step(
      'Inspect the Pod schema while moving through container fields',
      async () => {
        const yamlEditor = webview.locator('textarea');
        const specPanel = webview.getByRole('region', { name: 'Resource specification' });
        const specTitle = specPanel.locator('span.font-bold').first();

        await selectYamlLine(yamlEditor, 'kind: Pod');
        await expect(specTitle).toHaveText('Pod');
        await expect(specPanel.getByText('spec', { exact: true })).toBeVisible();

        await selectYamlLine(yamlEditor, '  containers:');
        await expect(specTitle).toHaveText('spec');
        await selectYamlLine(yamlEditor, '      image:');
        await expect(specTitle).toHaveText('containers');
        await expect(specPanel.getByText('containers[].image', { exact: true })).toBeVisible();
      },
      { params: { videoCaption: true } },
    );
  });
});
